In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/johnsmith88/heart-disease-dataset/heart.csv
/kaggle/input/datasets/oktayrdeki/heart-disease/heart_disease.csv

# Imports

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [3]:
import os
local_path = r"C:\Users\LENOVO\.cache\kagglehub\datasets\oktayrdeki\heart-disease\versions\1\heart_disease.csv"
if not os.path.exists(local_path):
    local_path = "heart_disease.csv"
df1 = pd.read_csv(local_path)
df1

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

# Data Cleaning

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [5]:
df1.isnull().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [6]:
# fill Age
df1["Age"] = df1["Age"].fillna(df1["Age"].mean())
# fill Blood Pressure
df1["Blood Pressure"] = df1["Blood Pressure"].fillna(df1["Blood Pressure"].mean())
#fill Sleep Hours
df1["Sleep Hours"] = df1["Sleep Hours"].fillna(df1["Sleep Hours"].mean())
# fill Alcohol Consumption
df1["Alcohol Consumption"] = df1["Alcohol Consumption"].fillna(0)
# fill BMI
df1["BMI"] = df1["BMI"].fillna(df1["BMI"].mean())
# fill CRP Level 
df1["CRP Level"] = df1["CRP Level"].fillna(df1["CRP Level"].mean())
# fill Homocysteine Level
df1["Homocysteine Level"] = df1["Homocysteine Level"].fillna(df1["Homocysteine Level"].mean())
# fill Triglyceride Level
df1["Triglyceride Level"] = df1["Triglyceride Level"].fillna(df1["Triglyceride Level"].mean())
# fill Fasting Blood Sugar
df1["Fasting Blood Sugar"] = df1["Fasting Blood Sugar"].fillna(df1["Fasting Blood Sugar"].mean())
# fill Cholesterol Level
df1["Cholesterol Level"] = df1["Cholesterol Level"].fillna(df1["Cholesterol Level"].mean())

In [7]:
# fix Stress Level , Sugar Consumption
df1.dropna(subset = [
    "Stress Level",
    "Sugar Consumption",
    "High Blood Pressure",
    "Low HDL Cholesterol",
    "High LDL Cholesterol",
    "Diabetes",
    "Family Heart Disease",
    "Gender",
    "Smoking",
    "Exercise Habits"
] , inplace = True)

In [8]:
df1

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,120.142213,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.000000,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.000000,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.000000,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.000000,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.000000,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,0,High,8.247784,Low,377.0,83.000000,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,0,Low,4.436762,Low,248.0,88.000000,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.000000,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.000000,14.387810,6.208531,Yes

In [9]:
df1.isnull().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
Low HDL Cholesterol     0
High LDL Cholesterol    0
Alcohol Consumption     0
Stress Level            0
Sleep Hours             0
Sugar Consumption       0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

# Mapping

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9751 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9751 non-null   float64
 1   Gender                9751 non-null   object
 2   Blood Pressure        9751 non-null   float64
 3   Cholesterol Level     9751 non-null   float64
 4   Exercise Habits       9751 non-null   object
 5   Smoking               9751 non-null   object
 6   Family Heart Disease  9751 non-null   object
 7   Diabetes              9751 non-null   object
 8   BMI                   9751 non-null   float64
 9   High Blood Pressure   9751 non-null   object
 10  Low HDL Cholesterol   9751 non-null   object
 11  High LDL Cholesterol  9751 non-null   object
 12  Alcohol Consumption   9751 non-null   object
 13  Stress Level          9751 non-null   object
 14  Sleep Hours           9751 non-null   float64
 15  Sugar Consumption     9751 non-null   object
 16  Triglyceride Level    9751 non-null   float64
 17  Fasting Blood Sugar   9751 non-null   float64
 18  CRP Level             9751 non-null   float64
 19  Homocysteine Level    9751 non-null   float64
 20  Heart Disease Status  9751 non-null   object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [12]:
all_columns = [
    "Gender",
    "Exercise Habits",
    "Smoking",
    "Family Heart Disease",
    "Diabetes",
    "High Blood Pressure",
    "Low HDL Cholesterol",
    "High LDL Cholesterol",
    "Alcohol Consumption",
    "Stress Level",
    "Sugar Consumption",
    "Heart Disease Status"]

In [13]:
encoders = {}
for col in all_columns :
    le = LabelEncoder()
    df1[col] = le.fit_transform(df1[col].astype(str))
    encoders[col] = le

# Data Spliting

In [14]:
X = df1.drop("Heart Disease Status" , axis = 1)
y = df1["Heart Disease Status"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

# Model taring

In [16]:
model = RandomForestClassifier(n_estimators=100,max_depth=None,random_state=42)

In [17]:
model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [18]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [20]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Overall Accuracy: {accuracy * 100:.2f}%")

Overall Accuracy: 79.96%

In [21]:
print(model.score(X, y))

0.9599015485591221

# Pickeling

In [ ]:
import pickle
import os
os.makedirs('../models', exist_ok=True)
with open('../models/heart_disease_model.pkl', 'wb') as f:
    pickle.dump(model, f)
with open('../models/heart_disease_encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)
with open('../models/heart_disease_columns.pkl', 'wb') as f:
    pickle.dump(list(X.columns), f)
print("Saved heart disease model, encoders, and columns successfully!")